//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetalApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public int id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string action { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual user user { get; set; }
    }
}
