//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetalApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brak
    {
        public int ID_Brak { get; set; }
        public Nullable<int> ID_rabota { get; set; }
        public string Prichina { get; set; }
    
        public virtual Rabota Rabota { get; set; }
    }
}
