//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetalApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detal()
        {
            this.Rabota = new HashSet<Rabota>();
        }
    
        public int ID_Detal { get; set; }
        public string NameDetal { get; set; }
        public string HarakteristiciDetali { get; set; }
        public System.TimeSpan VremyaNaIzgotovlenie { get; set; }
        public Nullable<int> ID_TD { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual TipDetali TipDetali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rabota> Rabota { get; set; }
    }
}
