//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetalApp.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class detalDbEntities : DbContext
    {
        public detalDbEntities()
            : base("name=detalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brak> Brak { get; set; }
        public virtual DbSet<Detal> Detal { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Rabota> Rabota { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipDetali> TipDetali { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
