//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetalApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rabota()
        {
            this.Brak = new HashSet<Brak>();
        }
    
        public int ID_rabota { get; set; }
        public Nullable<System.DateTime> DataNachalo { get; set; }
        public Nullable<System.DateTime> DataKonca { get; set; }
        public Nullable<System.TimeSpan> VremyaNachalo { get; set; }
        public Nullable<System.TimeSpan> VremyaKonca { get; set; }
        public Nullable<int> ID_Detal { get; set; }
        public Nullable<int> ID_Master { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brak> Brak { get; set; }
        public virtual Detal Detal { get; set; }
        public virtual Master Master { get; set; }
    }
}
